name: Run Graf Image Container

on:
  push:
    branches:
      - main

jobs:
  run_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Graf Image Container
        run: |
          CONTAINER_OUTPUT_PATH="$HOME/output.json"

          podman run --rm \
            -v "$GITHUB_WORKSPACE/grafana/perf/grafonnet":"/grafana/perf/grafonnet" \
            quay.io/rh-ee-kelchen/graf_image:latest

        

      - name: Upload output.json as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: graf-image-output
          path: $GITHUB_WORKSPACE/output.json
